export const invite = {
  partnerOne: "Aishwarya",
  partnerTwo: "Rohan",
  initials: "A · R",
  monogram: "AR",
  kicker: "शुभ सगाई",
  kickerEn: "The Ring Ceremony",
  tagline: "Two hearts. One ring.",
  inviteLine: "invite you to bless their ring ceremony",
  togetherLine: "Together with their families",
  familiesLine: "With blessings of both families",
  story:
    "Join us as two souls exchange rings, and a new chapter begins — surrounded by the people who made this yes possible.",
  eventTitle: "Aishwarya & Rohan — Ring Ceremony",
  dateLabel: "Monday",
  dateDisplay: "16",
  monthYear: "November 2026",
  dateLong: "Monday, 16 November 2026",
  timeLabel: "10 AM onwards",
  venueName: "Vivan's Sayali Lawns",
  venueArea: "Kaij Road, Prashant Nagar",
  venueCity: "Ambajogai, Maharashtra 431517",
  mapsUrl: "https://maps.app.goo.gl/WUca6EwQ7KjmbYiR6",
  dressCode: "Festive ethnic · Ivory, blush & gold",
  rsvpDeadline: "Kindly reply by 9 November",
  calendar: {
    start: "20261116T100000",
    end: "20261116T160000",
    timeZone: "Asia/Kolkata",
    startUtc: "20261116T043000Z",
    endUtc: "20261116T103000Z",
  },
  quote: "Two rings. One forever.",
} as const
