export const invite = {
  partnerOne: "Aishwarya",
  partnerTwo: "Rohan",
  initials: "A · R",
  monogram: "AR",
  ganesh: "श्री गणेशाय नमः",
  ganeshVerse: "वक्रतुंड महाकाय सूर्यकोटि समप्रभ",
  kicker: "शुभ सगाई",
  kickerEn: "Engagement Ceremony",
  tagline: "With elders' aashirwad, a sweet promise begins.",
  whisper: "An auspicious door awaits your blessing",
  sealCta: "Open the doors",
  inviteLine: "cordially invite you to bless their engagement",
  togetherLine: "Together with their families",
  familiesLine: "With the blessings of both families",
  story:
    "Join us as two families exchange aashirwad and two hearts exchange rings — the first sweet step of a lifelong journey.",
  eventTitle: "Aishwarya & Rohan — Ring Ceremony",
  dateLabel: "Monday",
  dateDisplay: "16",
  monthYear: "November 2026",
  dateLong: "Monday, 16 November 2026",
  timeLabel: "10 AM onwards",
  venueName: "Vivan's Sayali Lawns",
  venueArea: "Kaij Road, Prashant Nagar",
  venueCity: "Ambajogai, Maharashtra 431517",
  mapsUrl: "https://maps.app.goo.gl/WUca6EwQ7KjmbYiR6",
  dressCode: "Festive ethnic · Cream, rose & gold",
  rsvpDeadline: "Kindly reply by 9 November",
  calendar: {
    start: "20261116T100000",
    end: "20261116T160000",
    timeZone: "Asia/Kolkata",
    startUtc: "20261116T043000Z",
    endUtc: "20261116T103000Z",
  },
  quote: "May this sakharpuda sweeten every chapter ahead.",
} as const
